@uri = http://localhost:8080

### Sign In
# @name signIn
POST {{uri}}/api/v1/auth/sign-in
Content-Type: application/json

# {
#     "account": "jrmarcco@gmail.com",
#     "accountType": "email",
#     "credential": "<passwd>"
# }

{
    "account": "test-user-1@example.com",
    "accountType": "email",
    "credential": "hermet@2026"
}


### Refresh Access Token
POST {{uri}}/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "{{signIn.response.body.$.data.refreshToken}}"
}



### Add Contact Application
POST {{uri}}/api/v1/contact/apply
x-access-token: Bearer {{signIn.response.body.$.data.accessToken}}
Content-Type: application/json

{
    "contactId": 135343145434849280,
    "message": "hello hello!!!",
    "source": "search"
}


### Get Contact Applications
GET {{uri}}/api/v1/contact/applications
x-access-token: Bearer {{signIn.response.body.$.data.accessToken}}
Content-Type: application/json



### =======================================================
### Admin

### Add User
POST {{uri}}/api/v1/admin/user
x-access-token: Bearer {{signIn.response.body.$.data.accessToken}}
Content-Type: application/json

{
    "email": "test-user-1@example.com",
    "mobile": "13800138000",
    "nickname": "ciallo",
    "avatar": "",
    "gender": "female",
    "region": "",
    "birthday": 0,
    "tagline": ""
}
